server:
  port: 8081

# 自定义属性配置
original:
  config:
    title: OriginalConfig
    description: 主配置文件中属性

# 指定激活的环境
spring:
  profiles:
    active: gray



# 集合配置
aggregate:
  collection:
    # 数组
    arr: van,vanfan,dusty
    list:
      - van
      - vanfan
      - dusty
#    list:
#      [van, vanfan, dusty]
  # 对象集合
    bean:
      - appKey: vandusty
        appSecret: dusty.vip
      - appKey: van
        appSecret: VanFan
    map: {key: van, value: 风尘博客}
  #  map:
  #    key: van
  #    value: 风尘博客